// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StockAnalyzer.Core.Data;

#nullable disable

namespace StockAnalyzer.Core.Data.Migrations
{
    [DbContext(typeof(StockAnalyzerDbContext))]
    [Migration("20260127034243_AddImportanceScoreToSecurityMaster")]  // pragma: allowlist secret
    partial class AddImportanceScoreToSecurityMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.BusinessCalendarEntity", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsBusinessDay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsHoliday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLastBusinessDayMonthEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsMonthEnd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("SourceId", "EffectiveDate");

                    b.HasIndex("SourceId", "IsBusinessDay", "EffectiveDate")
                        .HasDatabaseName("IX_BusinessCalendar_SourceId_IsBusinessDay_EffectiveDate");

                    b.ToTable("BusinessCalendar", "data");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.CachedImageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ImageType")
                        .HasDatabaseName("IX_CachedImages_ImageType");

                    b.ToTable("CachedImages", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.CachedSentimentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyzerVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HeadlineHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsPending")
                        .HasColumnType("bit");

                    b.Property<decimal>("NegativeProb")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("NeutralProb")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PositiveProb")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<string>("Sentiment")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("HeadlineHash")
                        .IsUnique()
                        .HasDatabaseName("IX_CachedSentiments_HeadlineHash");

                    b.HasIndex("IsPending", "CreatedAt")
                        .HasDatabaseName("IX_CachedSentiments_Pending");

                    b.ToTable("CachedSentiments", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.PriceEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdjustedClose")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SecurityAlias")
                        .HasColumnType("int");

                    b.Property<decimal?>("Volatility")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveDate")
                        .HasDatabaseName("IX_Prices_EffectiveDate");

                    b.HasIndex("SecurityAlias", "EffectiveDate")
                        .IsUnique()
                        .HasDatabaseName("IX_Prices_SecurityAlias_EffectiveDate");

                    b.ToTable("Prices", "data");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.PriceStagingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AdjustedClose")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("date");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("pending");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long?>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("IX_PriceStaging_BatchId");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("IX_PriceStaging_Status_CreatedAt");

                    b.HasIndex("Ticker", "EffectiveDate")
                        .HasDatabaseName("IX_PriceStaging_Ticker_EffectiveDate");

                    b.ToTable("PriceStaging", "staging");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.SecurityMasterEntity", b =>
                {
                    b.Property<int>("SecurityAlias")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecurityAlias"));

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ImportanceScore")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsEodhdUnavailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTracked")
                        .HasColumnType("bit");

                    b.Property<string>("Isin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PrimaryAssetId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SecurityType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("SecurityAlias");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_SecurityMaster_IsActive");

                    b.HasIndex("IsTracked")
                        .HasDatabaseName("IX_SecurityMaster_IsTracked");

                    b.HasIndex("TickerSymbol")
                        .IsUnique()
                        .HasDatabaseName("IX_SecurityMaster_TickerSymbol");

                    b.HasIndex("IsActive", "IsTracked")
                        .HasDatabaseName("IX_SecurityMaster_IsActive_IsTracked");

                    b.ToTable("SecurityMaster", "data");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.SourceEntity", b =>
                {
                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceLongName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("SourceId");

                    b.HasIndex("SourceShortName")
                        .IsUnique()
                        .HasDatabaseName("IX_Sources_SourceShortName");

                    b.ToTable("Sources", "data");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.SymbolEntity", b =>
                {
                    b.Property<string>("Symbol")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("US");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplaySymbol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Figi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUpdated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Mic")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Symbol");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_Symbols_Description");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Symbols_Type");

                    b.HasIndex("Country", "IsActive")
                        .HasDatabaseName("IX_Symbols_Country_Active");

                    b.ToTable("Symbols", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.TickerHoldingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DollarValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Shares")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WatchlistId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistId");

                    b.ToTable("TickerHoldings", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.TrackedSecurityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("system");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("SecurityAlias")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Priority")
                        .HasDatabaseName("IX_TrackedSecurities_Priority");

                    b.HasIndex("SecurityAlias")
                        .IsUnique()
                        .HasDatabaseName("IX_TrackedSecurities_SecurityAlias");

                    b.HasIndex("Source")
                        .HasDatabaseName("IX_TrackedSecurities_Source");

                    b.ToTable("TrackedSecurities", "data");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.WatchlistEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WeightingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("equal");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.WatchlistTickerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("WatchlistId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WatchlistId");

                    b.ToTable("WatchlistTickers", (string)null);
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.BusinessCalendarEntity", b =>
                {
                    b.HasOne("StockAnalyzer.Core.Data.Entities.SourceEntity", "Source")
                        .WithMany("BusinessCalendarEntries")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Source");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.PriceEntity", b =>
                {
                    b.HasOne("StockAnalyzer.Core.Data.Entities.SecurityMasterEntity", "Security")
                        .WithMany("Prices")
                        .HasForeignKey("SecurityAlias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.TickerHoldingEntity", b =>
                {
                    b.HasOne("StockAnalyzer.Core.Data.Entities.WatchlistEntity", "Watchlist")
                        .WithMany("Holdings")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.TrackedSecurityEntity", b =>
                {
                    b.HasOne("StockAnalyzer.Core.Data.Entities.SecurityMasterEntity", "Security")
                        .WithOne()
                        .HasForeignKey("StockAnalyzer.Core.Data.Entities.TrackedSecurityEntity", "SecurityAlias")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.WatchlistTickerEntity", b =>
                {
                    b.HasOne("StockAnalyzer.Core.Data.Entities.WatchlistEntity", "Watchlist")
                        .WithMany("Tickers")
                        .HasForeignKey("WatchlistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Watchlist");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.SecurityMasterEntity", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.SourceEntity", b =>
                {
                    b.Navigation("BusinessCalendarEntries");
                });

            modelBuilder.Entity("StockAnalyzer.Core.Data.Entities.WatchlistEntity", b =>
                {
                    b.Navigation("Holdings");

                    b.Navigation("Tickers");
                });
#pragma warning restore 612, 618
        }
    }
}
